import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import ProductForm from "../components/ProductForm";
import ProductTable from "../components/ProductTable";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const { id } = router.query;

  useEffect(
    () => {
      if (!router.isReady) return;

    },
    [router.isReady]
  );
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Product System</h1>
        <ProductForm id={id} isEdit={id ? true : false} />
        <ProductTable />
      </main>
    </div>
  );
}
